### ISSUE TITLE
Issue in transformation function "epsgtoepsg"

### ISSUE THREAD

**Issue by ousim97** [davdmaccartney/Aerial-photos2Mosaic#1]
Hello, 

I'm actually testing your KGI-Aerial-photos2Mosaic.py python code and I'm facing the following error in the altitude function `IndexError: index 211237 is out of bounds for axis 0 with size 40000`
After some researches, I have discovered that the problem come up from the "epsgtoepsg" function that doesn't transform well the point coordinates from WGS84 to ETRS89 . 

Thanks in advance.

**Comment by davdmaccartney** [comment]
Hi I don't give any support for my code, but if the error is linked to OGR you should ask them, however you can also try to convert the WGS84 to UTM first and then UTM to ETRS89, good success.
